// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Judge","status":true,"description":"The judgement system on player.","parameters":{"Song Offset":"0","Song BPM":"150","Bar divisor":"4","Perfect timing cutoff":"100","Miss timing cutoff":"150","Checkout maximum bars count":"2","Event Action Invoker size":"2"}},
{"name":"StageManager","status":true,"description":"Controls the stage initialize and finalize.","parameters":{"Start Count Down Time":"3000","Song Name":"Dungeon1","Global Offset":"0"}},
{"name":"UIManager","status":true,"description":"The UI system on player.","parameters":{"Pool size":"5","Note Speed":"30"}}
];
